import type { BrandProfile } from "../types";
import { normalizeBrandProfile } from "../types";
import { buildThemeCss, type RepositoryFile } from "./repo-files";

type GitHubConfig = { owner: string; repo: string; baseBranch: string; token: string };

async function github<T>(config: GitHubConfig, path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      accept: "application/vnd.github+json",
      authorization: `Bearer ${config.token}`,
      "content-type": "application/json",
      "user-agent": "SundayMultipliedOnboarding/1.0",
      "x-github-api-version": "2022-11-28",
      ...init.headers,
    },
  });
  if (!response.ok) {
    const detail = (await response.text()).slice(0, 500);
    throw new Error(`GitHub ${response.status}: ${detail}`);
  }
  return (await response.json()) as T;
}

async function createFilesPullRequest(
  config: GitHubConfig,
  branchPrefix: string,
  commitMessage: string,
  title: string,
  body: string,
  files: RepositoryFile[],
): Promise<{ branch: string; pullRequestUrl: string }> {
  const ref = await github<{ object: { sha: string } }>(config, `/repos/${config.owner}/${config.repo}/git/ref/heads/${encodeURIComponent(config.baseBranch)}`);
  const baseCommit = await github<{ tree: { sha: string } }>(config, `/repos/${config.owner}/${config.repo}/git/commits/${ref.object.sha}`);
  const tree = await github<{ sha: string }>(config, `/repos/${config.owner}/${config.repo}/git/trees`, {
    method: "POST",
    body: JSON.stringify({ base_tree: baseCommit.tree.sha, tree: files.map((file) => ({ path: file.path, mode: "100644", type: "blob", content: file.content })) }),
  });
  const commit = await github<{ sha: string }>(config, `/repos/${config.owner}/${config.repo}/git/commits`, {
    method: "POST",
    body: JSON.stringify({ message: commitMessage, tree: tree.sha, parents: [ref.object.sha] }),
  });
  const branch = `${branchPrefix}-${Date.now()}`;
  await github(config, `/repos/${config.owner}/${config.repo}/git/refs`, { method: "POST", body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: commit.sha }) });
  const pull = await github<{ html_url: string }>(config, `/repos/${config.owner}/${config.repo}/pulls`, {
    method: "POST",
    body: JSON.stringify({ title, head: branch, base: config.baseBranch, body }),
  });
  return { branch, pullRequestUrl: pull.html_url };
}

export async function createOnboardingPullRequest(config: GitHubConfig, slug: string, churchName: string, files: RepositoryFile[]) {
  return createFilesPullRequest(
    config,
    `onboard/${slug}`,
    `onboard(${slug}): add church workspace`,
    `Onboard ${churchName}`,
    `## Church onboarding\n\nGenerated by the Sunday Multiplied onboarding agent.\n\n- Adds the church manifest and source URLs\n- Adds the client CSS override\n- Creates the weekly resource directory\n- Configures the shared approval dashboard\n\nReviewer contact details remain in the private onboarding agent state and are intentionally excluded from this repository. Confirm brand assets before merging.`,
    files,
  );
}

function decodeBase64(value: string): string {
  const binary = atob(value.replace(/\n/g, ""));
  const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0));
  return new TextDecoder().decode(bytes);
}

export async function loadChurchTheme(config: GitHubConfig, slug: string): Promise<{ slug: string; churchName: string; brand: BrandProfile; logoUrl: string }> {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error("Enter a valid church slug.");
  const file = await github<{ content: string }>(config, `/repos/${config.owner}/${config.repo}/contents/churches/${slug}/church.json?ref=${encodeURIComponent(config.baseBranch)}`);
  const manifest = JSON.parse(decodeBase64(file.content)) as { church?: { name?: string; slug?: string }; brand?: BrandProfile & { logoUrl?: string } };
  if (!manifest.church?.name) throw new Error("That church manifest does not contain a church name.");
  return {
    slug,
    churchName: manifest.church.name,
    brand: normalizeBrandProfile(manifest.brand),
    logoUrl: manifest.brand?.logoUrl || `/api/resource-assets/${slug}/logo`,
  };
}

export async function createThemeUpdatePullRequest(config: GitHubConfig, slug: string, brand: BrandProfile) {
  const file = await github<{ content: string }>(config, `/repos/${config.owner}/${config.repo}/contents/churches/${slug}/church.json?ref=${encodeURIComponent(config.baseBranch)}`);
  const manifest = JSON.parse(decodeBase64(file.content)) as Record<string, any>;
  const churchName = String(manifest?.church?.name || slug);
  const resolved = normalizeBrandProfile(brand);
  manifest.brand = { ...manifest.brand, ...resolved };
  const css = buildThemeCss(churchName, resolved);
  const files: RepositoryFile[] = [
    { path: `churches/${slug}/church.json`, content: `${JSON.stringify(manifest, null, 2)}\n` },
    { path: `churches/${slug}/styles/${slug}.css`, content: css },
    { path: `public/resources/${slug}/church.css`, content: css },
  ];
  return createFilesPullRequest(
    config,
    `theme/${slug}`,
    `theme(${slug}): update visual resource theme`,
    `Update ${churchName} resource theme`,
    `## Visual theme update\n\nGenerated from the Sunday Multiplied visual Theme Editor.\n\n- Updates structured brand/theme tokens in the church manifest\n- Regenerates the church resource stylesheet\n- Publishes the matching production stylesheet\n\nReview the rendered resource preview before merging.`,
    files,
  );
}
