import type { BrandProfile } from "../types";
import { normalizeBrandProfile } from "../types";
import { buildThemeCss, type RepositoryFile } from "./repo-files";

type GitHubConfig = { owner: string; repo: string; baseBranch: string; token: string };

async function github<T>(config: GitHubConfig, path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      accept: "application/vnd.github+json",
      authorization: `Bearer ${config.token}`,
      "content-type": "application/json",
      "user-agent": "SundayMultipliedOnboarding/1.0",
      "x-github-api-version": "2022-11-28",
      ...init.headers,
    },
  });
  if (!response.ok) {
    const detail = (await response.text()).slice(0, 500);
    throw new Error(`GitHub ${response.status}: ${detail}`);
  }
  return (await response.json()) as T;
}

async function createFilesPullRequest(config: GitHubConfig, branchPrefix: string, commitMessage: string, title: string, body: string, files: RepositoryFile[]): Promise<{ branch: string; pullRequestUrl: string }> {
  const ref = await github<{ object: { sha: string } }>(config, `/repos/${config.owner}/${config.repo}/git/ref/heads/${encodeURIComponent(config.baseBranch)}`);
  const baseCommit = await github<{ tree: { sha: string } }>(config, `/repos/${config.owner}/${config.repo}/git/commits/${ref.object.sha}`);
  const tree = await github<{ sha: string }>(config, `/repos/${config.owner}/${config.repo}/git/trees`, {
    method: "POST",
    body: JSON.stringify({ base_tree: baseCommit.tree.sha, tree: files.map((file) => ({ path: file.path, mode: "100644", type: "blob", content: file.content })) }),
  });
  const commit = await github<{ sha: string }>(config, `/repos/${config.owner}/${config.repo}/git/commits`, { method: "POST", body: JSON.stringify({ message: commitMessage, tree: tree.sha, parents: [ref.object.sha] }) });
  const branch = `${branchPrefix}-${Date.now()}`;
  await github(config, `/repos/${config.owner}/${config.repo}/git/refs`, { method: "POST", body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: commit.sha }) });
  const pull = await github<{ html_url: string }>(config, `/repos/${config.owner}/${config.repo}/pulls`, { method: "POST", body: JSON.stringify({ title, head: branch, base: config.baseBranch, body }) });
  return { branch, pullRequestUrl: pull.html_url };
}

export async function createOnboardingPullRequest(config: GitHubConfig, slug: string, churchName: string, files: RepositoryFile[]) {
  return createFilesPullRequest(config, `onboard/${slug}`, `onboard(${slug}): add church workspace`, `Onboard ${churchName}`, `## Church onboarding\n\nGenerated by the Sunday Multiplied onboarding agent.\n\n- Adds the church manifest and source URLs\n- Adds the client CSS override\n- Creates the weekly resource directory\n- Configures the shared approval dashboard\n\nReviewer contact details remain in the private onboarding agent state and are intentionally excluded from this repository. Confirm brand assets before merging.`, files);
}

function decodeBase64(value: string): string {
  const binary = atob(value.replace(/\n/g, ""));
  const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0));
  return new TextDecoder().decode(bytes);
}

async function readTextFile(config: GitHubConfig, path: string): Promise<string | undefined> {
  try {
    const file = await github<{ content: string }>(config, `/repos/${config.owner}/${config.repo}/contents/${path}?ref=${encodeURIComponent(config.baseBranch)}`);
    return decodeBase64(file.content);
  } catch { return undefined; }
}

export async function listChurchThemes(config: GitHubConfig): Promise<Array<{ slug: string; name: string }>> {
  const entries = await github<Array<{ name: string; type: string }>>(config, `/repos/${config.owner}/${config.repo}/contents/churches?ref=${encodeURIComponent(config.baseBranch)}`);
  const churches = await Promise.all(entries.filter((entry) => entry.type === "dir").map(async (entry) => {
    const rawManifest = await readTextFile(config, `churches/${entry.name}/church.json`);
    if (!rawManifest) return undefined;
    try {
      const manifest = JSON.parse(rawManifest) as { church?: { name?: string; slug?: string } };
      if (!manifest.church?.name) return undefined;
      return { slug: manifest.church.slug || entry.name, name: manifest.church.name };
    } catch { return undefined; }
  }));
  return churches.filter((church): church is { slug: string; name: string } => Boolean(church)).sort((a, b) => a.name.localeCompare(b.name));
}

function cssValue(css: string, property: string): string | undefined {
  const escaped = property.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return css.match(new RegExp(`${escaped}\\s*:\\s*([^;}{]+)`, "i"))?.[1]?.trim();
}
function blockValue(css: string, selectorPattern: string, property: string): string | undefined {
  const block = css.match(new RegExp(`${selectorPattern}\\s*\\{([^}]*)\\}`, "i"))?.[1] || "";
  return cssValue(block, property);
}
function hydrateBrandFromCss(profile: BrandProfile | undefined, css: string): BrandProfile {
  const current = normalizeBrandProfile(profile);
  const rootMap: Array<[keyof BrandProfile, string[]]> = [
    ["primaryColor", ["--sm-color-primary", "--sm-color-accent-dark"]],
    ["secondaryColor", ["--sm-color-secondary"]], ["accentColor", ["--sm-color-accent"]], ["backgroundColor", ["--sm-color-background"]],
    ["textColor", ["--sm-color-text"]], ["mutedColor", ["--sm-color-muted"]], ["borderColor", ["--sm-color-border"]],
    ["sectionBackgroundColor", ["--sm-color-section-background"]], ["calloutBackgroundColor", ["--sm-color-callout-background"]],
    ["headingFont", ["--sm-font-heading"]], ["bodyFont", ["--sm-font-body"]], ["cornerRadius", ["--sm-corner-radius", "--sm-radius"]],
    ["pageWidth", ["--sm-page-width"]], ["pagePadding", ["--sm-page-padding"]], ["sectionSpacing", ["--sm-section-spacing"]],
  ];
  const next: Record<string, unknown> = { ...current };
  for (const [key, properties] of rootMap) {
    const value = properties.map((property) => cssValue(css, property)).find(Boolean);
    if (value) next[key] = value;
  }
  const headerBackground = blockValue(css, "\\.sm-header(?:\\.sm-header--with-logo|\\s*,[^{}]*)?", "background");
  const prayerBackground = blockValue(css, "\\.sm-section--prayer", "background");
  const prayerText = blockValue(css, "\\.sm-section--prayer", "color");
  const scriptureBackground = blockValue(css, "\\.sm-scripture-text", "background");
  const questionBackground = blockValue(css, "\\.sm-question-group", "background");
  if (headerBackground && /^#[0-9a-f]{6}$/i.test(headerBackground)) next.headerBackgroundColor = headerBackground;
  if (prayerBackground && /^#[0-9a-f]{6}$/i.test(prayerBackground)) next.prayerBackgroundColor = prayerBackground;
  if (prayerText && /^#[0-9a-f]{6}$/i.test(prayerText)) next.prayerTextColor = prayerText;
  if (scriptureBackground && /^#[0-9a-f]{6}$/i.test(scriptureBackground)) next.scriptureBackgroundColor = scriptureBackground;
  if (questionBackground && /^#[0-9a-f]{6}$/i.test(questionBackground)) next.questionBackgroundColor = questionBackground;
  return normalizeBrandProfile(next as BrandProfile);
}

export async function loadChurchTheme(config: GitHubConfig, slug: string): Promise<{ slug: string; churchName: string; brand: BrandProfile; logoUrl: string }> {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error("Enter a valid church slug.");
  const rawManifest = await readTextFile(config, `churches/${slug}/church.json`);
  if (!rawManifest) throw new Error("That church configuration could not be found.");
  const manifest = JSON.parse(rawManifest) as { church?: { name?: string; slug?: string }; brand?: BrandProfile & { logoUrl?: string; stylesheet?: string } };
  if (!manifest.church?.name) throw new Error("That church manifest does not contain a church name.");
  const stylesheet = manifest.brand?.stylesheet || `churches/${slug}/styles/${slug}.css`;
  const mainCss = await readTextFile(config, stylesheet) || "";
  const overrideCss = await readTextFile(config, `churches/${slug}/styles/overrides.css`) || "";
  const brand = hydrateBrandFromCss(manifest.brand, `${mainCss}\n${overrideCss}`);
  return { slug, churchName: manifest.church.name, brand, logoUrl: manifest.brand?.logoUrl || `/api/resource-assets/${slug}/logo` };
}

export async function createThemeUpdatePullRequest(config: GitHubConfig, slug: string, brand: BrandProfile) {
  const rawManifest = await readTextFile(config, `churches/${slug}/church.json`);
  if (!rawManifest) throw new Error("That church configuration could not be found.");
  const manifest = JSON.parse(rawManifest) as Record<string, any>;
  const churchName = String(manifest?.church?.name || slug);
  const resolved = normalizeBrandProfile(brand);
  manifest.brand = { ...manifest.brand, ...resolved };
  const css = buildThemeCss(churchName, resolved);
  const files: RepositoryFile[] = [
    { path: `churches/${slug}/church.json`, content: `${JSON.stringify(manifest, null, 2)}\n` },
    { path: `churches/${slug}/styles/${slug}.css`, content: css },
    { path: `churches/${slug}/styles/overrides.css`, content: "/* Managed by the Sunday Multiplied Theme Editor. Manual overrides retired. */\n" },
    { path: `public/resources/${slug}/church.css`, content: css },
  ];
  return createFilesPullRequest(config, `theme/${slug}`, `theme(${slug}): update visual resource theme`, `Update ${churchName} resource theme`, `## Visual theme update\n\nGenerated from the Sunday Multiplied visual Theme Editor.\n\n- Updates structured brand/theme tokens in the church manifest\n- Regenerates the church resource stylesheet\n- Publishes the matching production stylesheet\n- Retires legacy manual overrides so the visual editor becomes the source of truth\n\nReview the rendered resource preview before merging.`, files);
}
