import type { RepositoryFile } from "./repo-files";

type GitHubConfig = {
  owner: string;
  repo: string;
  baseBranch: string;
  token: string;
};

async function github<T>(config: GitHubConfig, path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      accept: "application/vnd.github+json",
      authorization: `Bearer ${config.token}`,
      "content-type": "application/json",
      "user-agent": "SundayMultipliedOnboarding/1.0",
      "x-github-api-version": "2022-11-28",
      ...init.headers,
    },
  });
  if (!response.ok) {
    const detail = (await response.text()).slice(0, 500);
    throw new Error(`GitHub ${response.status}: ${detail}`);
  }
  return (await response.json()) as T;
}

function base64(value: string): string {
  const bytes = new TextEncoder().encode(value);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

export async function createOnboardingPullRequest(
  config: GitHubConfig,
  slug: string,
  churchName: string,
  files: RepositoryFile[],
): Promise<{ branch: string; pullRequestUrl: string }> {
  const ref = await github<{ object: { sha: string } }>(
    config,
    `/repos/${config.owner}/${config.repo}/git/ref/heads/${encodeURIComponent(config.baseBranch)}`,
  );
  const branch = `onboard/${slug}-${Date.now()}`;
  await github(config, `/repos/${config.owner}/${config.repo}/git/refs`, {
    method: "POST",
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: ref.object.sha }),
  });
  for (const file of files) {
    await github(config, `/repos/${config.owner}/${config.repo}/contents/${file.path}`, {
      method: "PUT",
      body: JSON.stringify({
        message: `onboard(${slug}): add ${file.path.split("/").at(-1)}`,
        content: base64(file.content),
        branch,
      }),
    });
  }
  const pull = await github<{ html_url: string }>(config, `/repos/${config.owner}/${config.repo}/pulls`, {
    method: "POST",
    body: JSON.stringify({
      title: `Onboard ${churchName}`,
      head: branch,
      base: config.baseBranch,
      body: `## Church onboarding\n\nGenerated by the Sunday Multiplied onboarding agent.\n\n- Adds the church manifest and source URLs\n- Adds the client CSS override\n- Creates the weekly resource directory\n- Configures the shared approval dashboard\n\nConfirm brand assets and reviewer details before merging.`,
    }),
  });
  return { branch, pullRequestUrl: pull.html_url };
}

