type RevisionRegenerationEnv = {
  DB?: D1Database;
  BUCKET?: R2Bucket;
  OPENAI_API_KEY?: string;
  OPENAI_MODEL?: string;
  APPROVAL_ADMIN_EMAIL?: string;
};

type RevisionRow = {
  id: string;
  packageId: string;
  resourceId: string;
  sourceVersion: number;
  sectionsJson: string;
  action: string;
  message: string | null;
  reviewerName: string;
  reviewerEmail: string | null;
  status: string;
  createdAt: string;
  packageTitle: string;
  weekOf: string;
  scripture: string | null;
  churchName: string;
  resourceKind: string;
  resourceTitle: string;
  previewUrl: string | null;
  generatedVersion?: number | null;
  generatedStorageKey?: string | null;
  generatedAt?: string | null;
};

const JSON_HEADERS = { "content-type": "application/json; charset=utf-8" };

const SECTION_MODIFIERS: Record<string, string[]> = {
  sermon_recap: ["summary"],
  key_takeaways: ["takeaways"],
  reflection: ["reflection"],
  prayer: ["prayer"],
  big_idea: ["big-idea"],
  tension: ["tension"],
  sermon_snapshot: ["summary"],
  key_moments: ["key-moments"],
  discussion_questions: ["questions"],
  practice: ["practice"],
  midweek: ["application"],
  leader_tip: ["leader-tip"],
  sermon_connection: ["family-remember", "summary", "big-idea"],
  scenario_activity: ["practice", "application"],
  application: ["application", "practice"],
};

export async function handleRevisionRegenerationApi(
  request: Request,
  env: RevisionRegenerationEnv,
): Promise<Response | null> {
  const url = new URL(request.url);
  const generateMatch = url.pathname.match(/^\/api\/revision-requests\/([^/]+)\/generate$/);
  const previewMatch = url.pathname.match(/^\/api\/revision-requests\/([^/]+)\/preview$/);
  const isList = url.pathname === "/api/revision-requests" && request.method === "GET";
  if (!isList && !generateMatch && !previewMatch) return null;

  if (!env.DB) return json({ error: "Approval database is not configured." }, 503);
  const authError = adminAuthorizationError(request, env);
  if (authError) return json({ error: authError }, 401);
  await ensureRevisionVersionSchema(env.DB);

  if (isList) return listRevisionRequests(env.DB);

  if (previewMatch && request.method === "GET") {
    if (!env.BUCKET) return new Response("Revision storage is not configured.", { status: 503 });
    const version = await env.DB.prepare(`
      SELECT storage_key AS storageKey
      FROM review_revision_versions
      WHERE revision_request_id = ?
      ORDER BY version DESC LIMIT 1
    `).bind(decodeURIComponent(previewMatch[1])).first<{ storageKey: string }>();
    if (!version?.storageKey) return new Response("Revised resource not found.", { status: 404 });
    const object = await env.BUCKET.get(version.storageKey);
    if (!object) return new Response("Revised resource file not found.", { status: 404 });
    return new Response(object.body, {
      headers: {
        "content-type": "text/html; charset=utf-8",
        "cache-control": "private, no-store",
        "x-robots-tag": "noindex, nofollow, noarchive",
        "x-content-type-options": "nosniff",
        "content-security-policy": "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; base-uri 'none'; frame-ancestors 'self'",
      },
    });
  }

  if (!generateMatch || request.method !== "POST") return null;
  if (!env.BUCKET) return json({ error: "Revision storage is not configured." }, 503);
  if (!env.OPENAI_API_KEY) return json({ error: "OPENAI_API_KEY is not configured for revision generation." }, 503);

  const revisionId = decodeURIComponent(generateMatch[1]);
  const revision = await loadRevision(env.DB, revisionId);
  if (!revision) return json({ error: "Revision request not found." }, 404);
  if (revision.status !== "pending") return json({ error: "This revision request is no longer pending." }, 409);

  const requestedSections = parseSections(revision.sectionsJson);
  if (requestedSections.includes("scripture")) {
    return json({ error: "Scripture text is source-controlled and cannot be regenerated by AI. Correct the Scripture reference/source separately before regenerating this resource." }, 422);
  }
  const unsupported = requestedSections.filter((section) => !SECTION_MODIFIERS[section]);
  if (unsupported.length) {
    return json({ error: `Targeted regeneration is not available yet for: ${unsupported.map(label).join(", ")}. Use a specific content section such as questions, practice/scenario, recap, takeaway, prayer, or application.` }, 422);
  }

  const production = productionSource(revision.previewUrl);
  if (!production) return json({ error: "This revision is not linked to a production-generated resource." }, 422);
  const sourceObject = await env.BUCKET.get(`production/jobs/${production.jobId}/${production.kind}.html`);
  const transcriptObject = await env.BUCKET.get(`production/jobs/${production.jobId}/transcript.txt`);
  if (!sourceObject || !transcriptObject) return json({ error: "The original production files required for revision are unavailable." }, 404);
  const sourceHtml = await sourceObject.text();
  const transcript = await transcriptObject.text();

  const targets: Array<{ section: string; modifier: string; innerHtml: string }> = [];
  for (const section of requestedSections) {
    const found = findSection(sourceHtml, SECTION_MODIFIERS[section]);
    if (!found) return json({ error: `Could not locate the ${label(section)} section in the reviewed resource.` }, 422);
    targets.push({ section, modifier: found.modifier, innerHtml: found.innerHtml });
  }

  let replacements: Array<{ section: string; innerHtml: string }>;
  try {
    replacements = await generateSectionReplacements(env, revision, targets, transcript);
  } catch (error) {
    console.error("revision_generation_failed", error);
    return json({ error: error instanceof Error ? clean(error.message, 500) : "Revision generation failed." }, 502);
  }

  let revisedHtml = sourceHtml;
  for (const target of targets) {
    const replacement = replacements.find((item) => item.section === target.section)?.innerHtml?.trim();
    if (!replacement) return json({ error: `Revision generation did not return ${label(target.section)}.` }, 502);
    revisedHtml = replaceSectionInner(revisedHtml, target.modifier, replacement);
  }

  const previous = await env.DB.prepare(`
    SELECT MAX(version) AS version FROM review_revision_versions WHERE revision_request_id = ?
  `).bind(revisionId).first<{ version: number | null }>();
  const nextVersion = Math.max(Number(revision.sourceVersion || 1) + 1, Number(previous?.version || 0) + 1);
  const storageKey = `production/jobs/${production.jobId}/revisions/${revisionId}/v${nextVersion}.html`;
  const now = new Date().toISOString();
  await env.BUCKET.put(storageKey, revisedHtml, { httpMetadata: { contentType: "text/html; charset=utf-8" } });
  await env.DB.prepare(`
    INSERT INTO review_revision_versions
      (id, revision_request_id, version, storage_key, status, created_at)
    VALUES (?, ?, ?, ?, 'ready_for_internal_review', ?)
  `).bind(crypto.randomUUID(), revisionId, nextVersion, storageKey, now).run();

  return json({
    ok: true,
    version: nextVersion,
    previewUrl: `/api/revision-requests/${encodeURIComponent(revisionId)}/preview`,
    status: "ready_for_internal_review",
  });
}

async function listRevisionRequests(db: D1Database) {
  const rows = await db.prepare(`
    SELECT rr.id, rr.package_id AS packageId, rr.resource_id AS resourceId,
           rr.source_version AS sourceVersion, rr.sections_json AS sectionsJson,
           rr.action, rr.message, rr.reviewer_name AS reviewerName,
           rr.reviewer_email AS reviewerEmail, rr.status, rr.created_at AS createdAt,
           p.title AS packageTitle, p.week_of AS weekOf, p.scripture,
           c.name AS churchName, r.kind AS resourceKind, r.title AS resourceTitle,
           r.preview_url AS previewUrl,
           rv.version AS generatedVersion, rv.storage_key AS generatedStorageKey,
           rv.status AS generationStatus, rv.created_at AS generatedAt
    FROM review_revision_requests rr
    JOIN review_packages p ON p.id = rr.package_id
    JOIN churches c ON c.id = p.church_id
    JOIN review_resources r ON r.id = rr.resource_id
    LEFT JOIN review_revision_versions rv ON rv.id = (
      SELECT id FROM review_revision_versions
      WHERE revision_request_id = rr.id
      ORDER BY version DESC LIMIT 1
    )
    WHERE rr.status = 'pending'
    ORDER BY rr.created_at DESC
  `).all<Record<string, unknown>>();
  return json({
    revisions: rows.results.map((row) => ({
      ...row,
      sections: parseSections(row.sectionsJson),
      sectionsJson: undefined,
      generatedPreviewUrl: row.generatedVersion ? `/api/revision-requests/${encodeURIComponent(String(row.id))}/preview` : null,
    })),
  });
}

async function loadRevision(db: D1Database, revisionId: string) {
  return db.prepare(`
    SELECT rr.id, rr.package_id AS packageId, rr.resource_id AS resourceId,
           rr.source_version AS sourceVersion, rr.sections_json AS sectionsJson,
           rr.action, rr.message, rr.reviewer_name AS reviewerName,
           rr.reviewer_email AS reviewerEmail, rr.status, rr.created_at AS createdAt,
           p.title AS packageTitle, p.week_of AS weekOf, p.scripture,
           c.name AS churchName, r.kind AS resourceKind, r.title AS resourceTitle,
           r.preview_url AS previewUrl
    FROM review_revision_requests rr
    JOIN review_packages p ON p.id = rr.package_id
    JOIN churches c ON c.id = p.church_id
    JOIN review_resources r ON r.id = rr.resource_id
    WHERE rr.id = ? LIMIT 1
  `).bind(revisionId).first<RevisionRow>();
}

async function generateSectionReplacements(
  env: RevisionRegenerationEnv,
  revision: RevisionRow,
  targets: Array<{ section: string; modifier: string; innerHtml: string }>,
  transcript: string,
) {
  const requested = targets.map((target) => target.section);
  const currentSections = targets.map((target) => `SECTION: ${target.section}\nCURRENT HTML:\n${target.innerHtml}`).join("\n\n");
  const prompt = `You are revising a Sunday Multiplied sermon-based discipleship resource after pastoral review.

RESOURCE: ${revision.resourceTitle} (${revision.resourceKind})
CHURCH: ${revision.churchName}
SERMON/PACKAGE: ${revision.packageTitle}
SCRIPTURE REFERENCE: ${revision.scripture || "not specified"}
REQUESTED SECTIONS: ${requested.join(", ")}
REVISION DIRECTION: ${revision.action.replaceAll("_", " ")}
PASTORAL NOTES: ${revision.message || "No additional notes."}

RULES:
- Stay faithful to the supplied sermon transcript. Never invent sermon claims, illustrations, quotations, or applications.
- Revise ONLY the requested sections. Everything else in the resource will be preserved byte-for-byte by the system.
- Return only INNER HTML for each requested section; do not return the outer <section> wrapper.
- Preserve the established Sunday Multiplied HTML classes used inside the current section when useful.
- Do not include <style>, <script>, stylesheet links, document wrappers, headers, or footers.
- Do not reproduce or alter Bible passage text. Scripture is controlled separately by the production system.
- For new_set on discussion questions, create a genuinely new set rather than light paraphrases of the old questions.
- For new_scenario, create a meaningfully different scenario/activity rooted in the sermon.
- Make questions open-ended, pastorally useful, and suitable for actual discussion rather than quiz-like recall unless the existing section specifically calls for observation.

CURRENT REQUESTED SECTION CONTENT:
${currentSections}`;

  const schema = {
    type: "object",
    additionalProperties: false,
    properties: {
      sections: {
        type: "array",
        minItems: requested.length,
        maxItems: requested.length,
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            section: { type: "string", enum: requested },
            innerHtml: { type: "string" },
          },
          required: ["section", "innerHtml"],
        },
      },
    },
    required: ["sections"],
  };

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: { authorization: `Bearer ${env.OPENAI_API_KEY}`, "content-type": "application/json" },
    body: JSON.stringify({
      model: env.OPENAI_MODEL || "gpt-5.6-terra",
      input: [
        { role: "system", content: [{ type: "input_text", text: prompt }] },
        { role: "user", content: [{ type: "input_text", text: transcript }] },
      ],
      text: { format: { type: "json_schema", name: "sunday_multiplied_revision", strict: true, schema } },
    }),
  });
  const data = await response.json() as {
    output_text?: string;
    output?: Array<{ content?: Array<{ type?: string; text?: string }> }>;
    error?: { message?: string };
  };
  if (!response.ok) throw new Error(data.error?.message || "Revision generation failed.");
  const outputText = data.output_text || extractOutputText(data.output);
  if (!outputText) throw new Error("Revision generation returned no output.");
  const parsed = JSON.parse(outputText) as { sections?: Array<{ section: string; innerHtml: string }> };
  if (!Array.isArray(parsed.sections)) throw new Error("Revision generation returned an invalid section payload.");
  return parsed.sections;
}

function findSection(html: string, modifiers: string[]) {
  for (const modifier of modifiers) {
    const pattern = new RegExp(`(<section\\b[^>]*class=["'][^"']*\\bsm-section--${escapeRegex(modifier)}\\b[^"']*["'][^>]*>)([\\s\\S]*?)(<\\/section>)`, "i");
    const match = html.match(pattern);
    if (match) return { modifier, innerHtml: match[2] };
  }
  return null;
}

function replaceSectionInner(html: string, modifier: string, innerHtml: string) {
  const pattern = new RegExp(`(<section\\b[^>]*class=["'][^"']*\\bsm-section--${escapeRegex(modifier)}\\b[^"']*["'][^>]*>)[\\s\\S]*?(<\\/section>)`, "i");
  if (!pattern.test(html)) throw new Error(`Could not replace ${modifier} section.`);
  return html.replace(pattern, `$1\n${innerHtml.trim()}\n$2`);
}

function productionSource(previewUrl: string | null) {
  if (!previewUrl) return null;
  const match = previewUrl.match(/\/api\/production\/preview\/([^/]+)\/(monday|group|family)(?:$|[?#])/i);
  return match ? { jobId: match[1], kind: match[2].toLowerCase() } : null;
}

async function ensureRevisionVersionSchema(db: D1Database) {
  await db.batch([
    db.prepare(`CREATE TABLE IF NOT EXISTS review_revision_versions (
      id TEXT PRIMARY KEY NOT NULL,
      revision_request_id TEXT NOT NULL,
      version INTEGER NOT NULL,
      storage_key TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'ready_for_internal_review',
      created_at TEXT NOT NULL
    )`),
    db.prepare("CREATE INDEX IF NOT EXISTS review_revision_versions_request_idx ON review_revision_versions(revision_request_id)"),
  ]);
}

function parseSections(value: unknown): string[] {
  if (typeof value !== "string") return [];
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string") : [];
  } catch {
    return [];
  }
}

function extractOutputText(output: Array<{ content?: Array<{ type?: string; text?: string }> }> | undefined) {
  if (!output) return "";
  return output.flatMap((item) => item.content || [])
    .filter((item) => item.type === "output_text" && typeof item.text === "string")
    .map((item) => item.text || "")
    .join("");
}

function escapeRegex(value: string) { return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function clean(value: string, maxLength: number) { return value.replace(/[\u0000-\u001f\u007f]/g, " ").trim().slice(0, maxLength); }

function adminAuthorizationError(request: Request, env: RevisionRegenerationEnv) {
  const email = accessIdentityEmail(request);
  const adminEmail = env.APPROVAL_ADMIN_EMAIL?.trim() || "brian@sundaymultiplied.com";
  if (!email || email.toLowerCase() !== adminEmail.toLowerCase()) return "Unauthorized.";
  return "";
}

function accessIdentityEmail(request: Request) {
  const headerEmail = request.headers.get("cf-access-authenticated-user-email")
    ?? request.headers.get("oai-authenticated-user-email");
  if (headerEmail) return headerEmail.trim();
  const assertion = request.headers.get("cf-access-jwt-assertion");
  const payload = assertion?.split(".")[1];
  if (!payload) return "";
  try {
    const base64 = payload.replaceAll("-", "+").replaceAll("_", "/").padEnd(Math.ceil(payload.length / 4) * 4, "=");
    const claims = JSON.parse(atob(base64)) as { email?: unknown };
    return typeof claims.email === "string" ? claims.email.trim() : "";
  } catch {
    return "";
  }
}

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...JSON_HEADERS, "cache-control": "no-store", "x-content-type-options": "nosniff" },
  });
}
